CREATE TABLE [dbo].[tbl_PortfolioFundLegal] (
    [PortfolioFundLegalID]    INT           IDENTITY (1, 1) NOT NULL,
    [VehicleID]               INT           NULL,
    [Vehicle]                 VARCHAR (MAX) NULL,
    [ConstitutionDate]        DATETIME      NULL,
    [EndSubscriptionPeriod]   DATETIME      NULL,
    [FundDuration]            VARCHAR (MAX) NULL,
    [InvestmentStrategy]      VARCHAR (MAX) NULL,
    [GeographicalCoverage]    VARCHAR (MAX) NULL,
    [EndInvestmentPeriod]     DATETIME      NULL,
    [ManagementFees]          VARCHAR (MAX) NULL,
    [DateAccountingPeriod]    DATETIME      NULL,
    [FundProfile]             VARCHAR (MAX) NULL,
    [InvestmentsPeriod]       VARCHAR (MAX) NULL,
    [InvestmentInstrument]    VARCHAR (MAX) NULL,
    [LastDevelopments]        VARCHAR (MAX) NULL,
    [ExitsPeriod]             VARCHAR (MAX) NULL,
    [CallsAndDistributions]   VARCHAR (MAX) NULL,
    [NAV]                     VARCHAR (MAX) NULL,
    [FundProfileFR]           VARCHAR (MAX) NULL,
    [InvestmentsPeriodFR]     VARCHAR (MAX) NULL,
    [InvestmentInstrumentFR]  VARCHAR (MAX) NULL,
    [LastDevelopmentsFR]      VARCHAR (MAX) NULL,
    [ExitsPeriodFR]           VARCHAR (MAX) NULL,
    [CallsAndDistributionsFR] VARCHAR (MAX) NULL,
    [NAVFR]                   VARCHAR (MAX) NULL,
    [Associate]               VARCHAR (MAX) NULL,
    [FIAManager]              VARCHAR (MAX) NULL,
    [Active]                  BIT           NULL,
    [CreatedBy]               VARCHAR (50)  NULL,
    [CreatedDateTime]         DATETIME      NULL,
    [ModifiedBy]              VARCHAR (50)  NULL,
    [ModifiedDateTime]        DATETIME      NULL,
    CONSTRAINT [PK_tbl_PortfolioFundLegal] PRIMARY KEY CLUSTERED ([PortfolioFundLegalID] ASC)
);

