CREATE TABLE [dbo].[tbl_VehicleNav] (
    [VehicleNavID]                     INT             IDENTITY (1, 1) NOT NULL,
    [VehicleID]                        INT             NULL,
    [NavDate]                          DATETIME        NULL,
    [PortfolioNAV]                     DECIMAL (18, 6) NULL,
    [WorkingCapital]                   DECIMAL (18, 6) NULL,
    [Cash]                             DECIMAL (18, 6) NULL,
    [Other]                            DECIMAL (18, 6) NULL,
    [Audited]                          BIT             NULL,
    [Notes]                            VARCHAR (4000)  NULL,
    [Active]                           BIT             NULL,
    [CreatedDateTime]                  DATETIME        NULL,
    [CreatedBy]                        VARCHAR (20)    NULL,
    [ModifiedDateTime]                 DATETIME        NULL,
    [ModifiedBy]                       VARCHAR (20)    NULL,
    [IsApproved1]                      BIT             NULL,
    [Log1]                             VARCHAR (1000)  NULL,
    [IsApproved2]                      BIT             NULL,
    [Log2]                             VARCHAR (1000)  NULL,
    [TotalValidationReq]               INT             NULL,
    [UserRole1]                        VARCHAR (1000)  NULL,
    [UserRole2]                        VARCHAR (1000)  NULL,
    [Expenses]                         DECIMAL (18, 6) NULL,
    [UnrealizedHedging]                DECIMAL (18, 6) NULL,
    [DocStatus]                        INT             NULL,
    [RealisedGains]                    DECIMAL (18, 6) NULL,
    [OperatingProfits]                 DECIMAL (18, 6) NULL,
    [GainLossesRevaluationToFV]        DECIMAL (18, 6) NULL,
    [CarriedInterestAccrued]           DECIMAL (18, 6) NULL,
    [TransactionFees]                  DECIMAL (18, 6) NULL,
    [GPFees]                           DECIMAL (18, 6) NULL,
    [CashOverDraft]                    DECIMAL (18, 6) NULL,
    [RevenueExpenses]                  DECIMAL (18, 6) NULL,
    [Revenue]                          DECIMAL (18, 6) NULL,
    [Expenses1]                        DECIMAL (18, 6) NULL,
    [NetSurplusDeficit]                DECIMAL (18, 6) NULL,
    [NetSurplusPeriod]                 DECIMAL (18, 6) NULL,
    [ExpensesManagementFees]           DECIMAL (18, 6) NULL,
    [ExpensesTransactionFees]          DECIMAL (18, 6) NULL,
    [ExpensesAbortionFees]             DECIMAL (18, 6) NULL,
    [ExpensesOthers]                   DECIMAL (18, 6) NULL,
    [RealizsedMarketableSecurities]    DECIMAL (18, 6) NULL,
    [RealizsedPortfolioInvestments]    DECIMAL (18, 6) NULL,
    [UnrealisedMarketableSecurities]   DECIMAL (18, 6) NULL,
    [UnrealisedAccruedInterest]        DECIMAL (18, 6) NULL,
    [UnrealisedRevaluationInvestments] DECIMAL (18, 6) NULL,
    [RetainedProceeds]                 DECIMAL (18, 6) NULL,
    [UnrealisedGains]                  DECIMAL (18, 6) NULL,
    [PotentialLiabilities]             DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_tbl_VehicleNav] PRIMARY KEY CLUSTERED ([VehicleNavID] ASC)
);

