CREATE TABLE [dbo].[tbl_PortfolioTransactionStructure] (
    [TransactionStructureID]   INT             IDENTITY (1, 1) NOT NULL,
    [PortfolioID]              INT             NULL,
    [ClosingDate]              DATETIME        NULL,
    [DealYear]                 VARCHAR (50)    NULL,
    [EBITX]                    DECIMAL (18, 6) NULL,
    [EBITDAX]                  DECIMAL (18, 6) NULL,
    [PE]                       DECIMAL (18, 6) NULL,
    [EnterpriseValue]          DECIMAL (18, 6) NULL,
    [NetCash]                  DECIMAL (18, 6) NULL,
    [SharesAmount]             DECIMAL (18, 6) NULL,
    [InvestmentAmount]         DECIMAL (18, 6) NULL,
    [CurrentAccount1]          DECIMAL (18, 6) NULL,
    [DividendsToShareholders]  DECIMAL (18, 6) NULL,
    [EarnOutAmount]            DECIMAL (18, 6) NULL,
    [DebtReimbursementAmount]  DECIMAL (18, 6) NULL,
    [FeesWorkingCapitalAmount] DECIMAL (18, 6) NULL,
    [CashAmount]               DECIMAL (18, 6) NULL,
    [ShareCapital]             DECIMAL (18, 6) NULL,
    [ConvertibleBonds]         DECIMAL (18, 6) NULL,
    [CurrentAccount2]          DECIMAL (18, 6) NULL,
    [Mezzanine]                DECIMAL (18, 6) NULL,
    [VendorLoan]               DECIMAL (18, 6) NULL,
    [Bonds]                    DECIMAL (18, 6) NULL,
    [BulletDebt]               DECIMAL (18, 6) NULL,
    [SeniorDebt]               DECIMAL (18, 6) NULL,
    [ShortTermLoan]            DECIMAL (18, 6) NULL,
    [BridgeLoan]               DECIMAL (18, 6) NULL,
    [Dividends]                DECIMAL (18, 6) NULL,
    [Turnover]                 DECIMAL (18, 6) NULL,
    [EBITDA]                   DECIMAL (18, 6) NULL,
    [EBIT]                     DECIMAL (18, 6) NULL,
    [Workingcapital]           DECIMAL (18, 6) NULL,
    [CAPEX]                    DECIMAL (18, 6) NULL,
    [Netcash_STdebt]           DECIMAL (18, 6) NULL,
    [Financialdebt]            DECIMAL (18, 6) NULL,
    [Active]                   BIT             CONSTRAINT [DF_tbl_PortfolioTransactionStructure_Active] DEFAULT ((1)) NULL,
    [CreatedDateTime]          DATETIME        NULL,
    [ModifiedDateTime]         DATETIME        NULL,
    [CreatedBy]                VARCHAR (100)   NULL,
    [ModifiedBy]               VARCHAR (100)   NULL,
    [NetProfit]                DECIMAL (18, 6) NULL,
    [Workforce]                DECIMAL (18, 6) NULL,
    [ClosingDateExit]          DATETIME        NULL,
    CONSTRAINT [PK_tbl_PortfolioTransactionStructure] PRIMARY KEY CLUSTERED ([TransactionStructureID] ASC)
);

