CREATE TABLE [dbo].[tbl_VehicleLegal] (
    [VehicleLegalID]              INT            IDENTITY (1, 1) NOT NULL,
    [VehicleID]                   INT            NULL,
    [FirstClosingOn]              DATE           NULL,
    [FinalClosingOn]              DATE           NULL,
    [LegalVehicleID]              VARCHAR (MAX)  NULL,
    [ReportingFrequencyID]        INT            NULL,
    [ReportingLimitPeriod]        INT            NULL,
    [ReportingValuationID]        INT            NULL,
    [LegalStructureID]            INT            NULL,
    [InvestmentPeriodYears]       INT            NULL,
    [InvestmentPeriodMonths]      INT            NULL,
    [DurationPeriodYears]         INT            NULL,
    [DurationPeriodMonths]        INT            NULL,
    [AdditionalYears]             INT            NULL,
    [ReportingObligations]        VARCHAR (MAX)  NULL,
    [LegalNotes]                  VARCHAR (MAX)  NULL,
    [FiscalNotes]                 VARCHAR (MAX)  NULL,
    [CreatedDateTime]             DATETIME       NULL,
    [CreatedBy]                   VARCHAR (100)  NULL,
    [ModifiedDateTime]            DATETIME       NULL,
    [ModifiedBy]                  VARCHAR (100)  NULL,
    [Active]                      BIT            NULL,
    [ISIN]                        VARCHAR (1000) NULL,
    [Company1]                    INT            NULL,
    [Company2]                    INT            NULL,
    [Company3]                    INT            NULL,
    [Company4]                    INT            NULL,
    [TotalCommitments]            VARCHAR (MAX)  NULL,
    [FundDomiciliation]           VARCHAR (MAX)  NULL,
    [Custodian]                   VARCHAR (MAX)  NULL,
    [CentralAdministrator]        VARCHAR (MAX)  NULL,
    [LegalAdvisor]                VARCHAR (MAX)  NULL,
    [CAC]                         VARCHAR (MAX)  NULL,
    [AIFM]                        VARCHAR (MAX)  NULL,
    [EngagementsTotaux]           VARCHAR (MAX)  NULL,
    [Terme]                       VARCHAR (MAX)  NULL,
    [StrategieInvestissement]     VARCHAR (MAX)  NULL,
    [CouvertureGeographique]      VARCHAR (MAX)  NULL,
    [LegalVehicleIDFr]            VARCHAR (MAX)  NULL,
    [ReportingObligationsFr]      VARCHAR (MAX)  NULL,
    [CarriedInterest]             VARCHAR (MAX)  NULL,
    [Hurdle]                      VARCHAR (MAX)  NULL,
    [Valorisator]                 VARCHAR (MAX)  NULL,
    [MainRisks]                   VARCHAR (MAX)  NULL,
    [ReportingStandards]          VARCHAR (MAX)  NULL,
    [ManagementFees]              VARCHAR (MAX)  NULL,
    [Distributions]               VARCHAR (MAX)  NULL,
    [EndOfInvestmentPeriod]       DATETIME       NULL,
    [CarriedInterestFR]           VARCHAR (MAX)  NULL,
    [HurdleFR]                    VARCHAR (MAX)  NULL,
    [MainRisksFR]                 VARCHAR (MAX)  NULL,
    [ManagementFeesFR]            VARCHAR (MAX)  NULL,
    [DistributionsFR]             VARCHAR (MAX)  NULL,
    [TeamCommitment]              VARCHAR (MAX)  NULL,
    [EndDateAccountingYear]       VARCHAR (MAX)  NULL,
    [StartInvestmentPeriod]       DATETIME       NULL,
    [EndInvestmentPeriod]         DATETIME       NULL,
    [InvestmentPeriodCriteria]    VARCHAR (MAX)  NULL,
    [ManagementFeeTerms]          VARCHAR (MAX)  NULL,
    [CapitalAvailableInvestments] VARCHAR (MAX)  NULL,
    [DistributionWaterfall]       VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_tbl_VehicleLegal] PRIMARY KEY CLUSTERED ([VehicleLegalID] ASC),
    CONSTRAINT [VehicleLegalVehicleID] FOREIGN KEY ([VehicleID]) REFERENCES [dbo].[tbl_Vehicle] ([VehicleID])
);


GO
ALTER TABLE [dbo].[tbl_VehicleLegal] NOCHECK CONSTRAINT [VehicleLegalVehicleID];


GO
CREATE NONCLUSTERED INDEX [IX_tbl_VehicleLegal]
    ON [dbo].[tbl_VehicleLegal]([VehicleID] ASC);

