CREATE TABLE [dbo].[tbl_VehicleEligibility] (
    [VehicleEligibilityID]      INT             IDENTITY (1, 1) NOT NULL,
    [VehicleID]                 INT             NULL,
    [VehicleEligibilityTypeID]  INT             NULL,
    [LegalTypeVehicleID]        INT             NULL,
    [ConstitutionDate]          DATE            NULL,
    [LiquidationDate]           DATE            NULL,
    [LimitDate]                 DATE            NULL,
    [SubscriptionPeriodDate]    DATE            NULL,
    [EligibilityRatio50Date]    DATE            NULL,
    [EligibilityRatio0Date]     DATE            NULL,
    [PercentageEligibile]       DECIMAL (18, 2) NULL,
    [MinEmp]                    INT             NULL,
    [MaxEmp]                    INT             NULL,
    [HeadquartarID]             INT             NULL,
    [MinCapital]                DECIMAL (18, 2) NULL,
    [MinRate5Years]             DECIMAL (18, 2) NULL,
    [MinRate8Years]             DECIMAL (18, 2) NULL,
    [MaxReglementedMarket]      DECIMAL (18, 2) NULL,
    [MaxNonReglementedMarket]   DECIMAL (18, 2) NULL,
    [MinRatioCapitalIncrease]   DECIMAL (18, 2) NULL,
    [MaxRatioCapitalIncrease]   DECIMAL (18, 2) NULL,
    [MinRatioConvertibaleBonds] DECIMAL (18, 2) NULL,
    [MaxRatioConvertibaleBonds] DECIMAL (18, 2) NULL,
    [MinTransferSecurity]       DECIMAL (18, 2) NULL,
    [MaxTransferSecurity]       DECIMAL (18, 2) NULL,
    [MinCurrentAccount]         DECIMAL (18, 2) NULL,
    [MaxCurrentAccount]         DECIMAL (18, 2) NULL,
    [Active]                    BIT             NULL,
    [CreatedDateTime]           DATETIME        NULL,
    [ModifiedDateTime]          DATETIME        NULL,
    [CreatedBy]                 VARCHAR (100)   NULL,
    [ModifiedBy]                VARCHAR (100)   NULL,
    [AgrementDate]              DATETIME        NULL,
    [MaximaleDate]              DATETIME        NULL,
    CONSTRAINT [PK_tbl_VehicleEligibility] PRIMARY KEY CLUSTERED ([VehicleEligibilityID] ASC)
);

