ALTER ROLE [db_owner] ADD MEMBER [LBOFFICE\davigold];


GO
ALTER ROLE [db_owner] ADD MEMBER [LBOFFICE\aims];


GO
ALTER ROLE [db_owner] ADD MEMBER [davigold];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT Service\MSSQLSERVER];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT AUTHORITY\LOCAL SERVICE];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT AUTHORITY\NETWORK SERVICE];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT AUTHORITY\SYSTEM];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT SERVICE\SQLSERVERAGENT];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT SERVICE\Winmgmt];


GO
ALTER ROLE [db_owner] ADD MEMBER [spdev];


GO
ALTER ROLE [db_owner] ADD MEMBER [DESKTOP-J7U4UF5\Administrator];

