  
CREATE PROC [dbo].[GetPortfolioTransactionstructure](@portfolioID INT)    
AS    
     SELECT TransactionStructureID,     
            PortfolioID,     
            ClosingDate,    
   ClosingDateExit,  
            DealYear,     
            EBITX,     
            EBITDAX,     
            PE,     
            EnterpriseValue,     
            NetCash,     
            SharesAmount,     
            InvestmentAmount,     
            CurrentAccount1,     
            DividendsToShareholders,     
            EarnOutAmount,     
            DebtReimbursementAmount,     
            FeesWorkingCapitalAmount,     
            CashAmount,     
            ShareCapital,     
            ConvertibleBonds,     
            CurrentAccount2,     
            Mezzanine,     
            VendorLoan,     
            Bonds,     
            BulletDebt,     
            SeniorDebt,     
            ShortTermLoan,     
            BridgeLoan,     
            Dividends,     
            [Turnover],     
            [EBITDA],     
            [EBIT],     
            [Workingcapital],     
            [CAPEX],     
            [Netcash_STdebt],     
            [Financialdebt],     
            Active,     
            CreatedDateTime,     
            ModifiedDateTime,     
            CreatedBy,     
            ModifiedBy,     
            NetProfit,     
            Workforce    
     FROM tbl_portfolioTransactionstructure    
     WHERE portfolioID = @portfolioID; 