CREATE PROC [dbo].[SetPortfolioTransactionstructure]    
(@PortfolioID              INT            = NULL,     
 @ClosingDate              DATETIME       = NULL,     
 @ClosingDateExit              DATETIME       = NULL,     
 @DealYear                 VARCHAR(50)    = NULL,     
 @EBITX                    DECIMAL(18, 6)  = NULL,     
 @EBITXDAX                 DECIMAL(18, 6)  = NULL,     
 @PE                       DECIMAL(18, 6)  = NULL,     
 @EnterpriseValue          DECIMAL(18, 6)  = NULL,     
 @NetCash                  DECIMAL(18, 6)  = NULL,     
 @SharesAmount             DECIMAL(18, 6)  = NULL,     
 @InvestmentAmount         DECIMAL(18, 6)  = NULL,     
 @CurrentAccount1          DECIMAL(18, 6)  = NULL,     
 @DividendsToShareholders  DECIMAL(18, 6)  = NULL,     
 @EarnOutAmount            DECIMAL(18, 6)  = NULL,     
 @DebtReimbursementAmount  DECIMAL(18, 6)  = NULL,     
 @FeesWorkingCapitalAmount DECIMAL(18, 6)  = NULL,     
 @CashAmount               DECIMAL(18, 6)  = NULL,     
 @ShareCapital             DECIMAL(18, 6)  = NULL,     
 @ConvertibleBonds         DECIMAL(18, 6)  = NULL,     
 @CurrentAccount2          DECIMAL(18, 6)  = NULL,     
 @Mezzanine                DECIMAL(18, 6)  = NULL,     
 @VendorLoan               DECIMAL(18, 6)  = NULL,     
 @Bonds                    DECIMAL(18, 6)  = NULL,     
 @BulletDebt               DECIMAL(18, 6)  = NULL,     
 @SeniorDebt               DECIMAL(18, 6)  = NULL,     
 @ShortTermLoan            DECIMAL(18, 6)  = NULL,     
 @BridgeLoan               DECIMAL(18, 6)  = NULL,     
 @Dividends                DECIMAL(18, 6)  = NULL,     
 @Turnover                 DECIMAL(18, 6)  = NULL,     
 @EBITDA                   DECIMAL(18, 6)  = NULL,     
 @EBIT                     DECIMAL(18, 6)  = NULL,     
 @Workingcapital           DECIMAL(18, 6)  = NULL,     
 @CAPEX                    DECIMAL(18, 6)  = NULL,     
 @Netcash_STdebt           DECIMAL(18, 6)  = NULL,     
 @Financialdebt            DECIMAL(18, 6)  = NULL,     
 @CreatedBy                VARCHAR(100)   = NULL,     
 @NetProfit                DECIMAL(18, 6)  = NULL,     
 @Workforce                DECIMAL(18, 6)  = NULL    
)    
AS    
     DECLARE @TransactionStructureID INT;    
     IF NOT EXISTS    
     (    
         SELECT TOP 1 1    
         FROM tbl_portfolioTransactionstructure    
         WHERE PortfolioID = @portfolioID    
     )    
         BEGIN    
             INSERT INTO tbl_portfolioTransactionstructure    
             (PortfolioID,     
              ClosingDate,    
     ClosingDateExit,  
              DealYear,     
              EBITX,     
              EBITDAX,     
              PE,     
              EnterpriseValue,     
              NetCash,     
              SharesAmount,     
              InvestmentAmount,     
              CurrentAccount1,     
              DividendsToShareholders,     
              EarnOutAmount,     
              DebtReimbursementAmount,     
              FeesWorkingCapitalAmount,     
              CashAmount,     
              ShareCapital,     
              ConvertibleBonds,     
              CurrentAccount2,     
              Mezzanine,     
              VendorLoan,     
              Bonds,     
              BulletDebt,     
              SeniorDebt,     
              ShortTermLoan,     
              BridgeLoan,     
              Dividends,     
              CreatedDateTime,     
              CreatedBy,     
              Turnover,     
              EBITDA,     
              EBIT,     
              Workingcapital,     
              CAPEX,     
              Netcash_STdebt,     
              Financialdebt,     
              NetProfit,     
              Workforce    
             )    
                    SELECT @PortfolioID,     
                           @ClosingDate,     
         @ClosingDateExit,  
                           @DealYear,     
                           @EBITX,     
                           @EBITXDAX,     
                           @PE,     
                           @EnterpriseValue,     
                      @NetCash,     
                           @SharesAmount,     
                           @InvestmentAmount,     
                           @CurrentAccount1,     
                           @DividendsToShareholders,     
                           @EarnOutAmount,     
  @DebtReimbursementAmount,     
                           @FeesWorkingCapitalAmount,     
                           @CashAmount,     
                           @ShareCapital,     
                           @ConvertibleBonds,     
                           @CurrentAccount2,     
                           @Mezzanine,     
                           @VendorLoan,     
                           @Bonds,     
                           @BulletDebt,     
                           @SeniorDebt,     
                           @ShortTermLoan,     
                           @BridgeLoan,     
                           @Dividends,     
                           GETDATE(),     
                           @CreatedBy,     
                           @Turnover,     
                           @EBITDA,     
                           @EBIT,     
                           @Workingcapital,     
                           @CAPEX,     
                           @Netcash_STdebt,     
                           @Financialdebt,     
                           @NetProfit,     
                           @Workforce;    
             SET @TransactionStructureID = SCOPE_IDENTITY();    
     END;    
         ELSE    
         BEGIN    
             UPDATE tbl_portfolioTransactionstructure    
               SET     
                   ClosingDate = @ClosingDate,     
       ClosingDateExit = @ClosingDateExit,  
                   DealYear = @DealYear,     
                   EBITX = @EBITX,     
                   EBITDAX = @EBITXDAX,     
                   PE = @PE,     
                   EnterpriseValue = @EnterpriseValue,     
                   NetCash = @NetCash,     
                   SharesAmount = @SharesAmount,     
                   InvestmentAmount = @InvestmentAmount,     
                   CurrentAccount1 = @CurrentAccount1,     
                   DividendsToShareholders = @DividendsToShareholders,     
                   EarnOutAmount = @EarnOutAmount,     
                   DebtReimbursementAmount = @DebtReimbursementAmount,     
                   FeesWorkingCapitalAmount = @FeesWorkingCapitalAmount,     
                   CashAmount = @CashAmount,     
                   ShareCapital = @ShareCapital,     
                   ConvertibleBonds = @ConvertibleBonds,     
                   CurrentAccount2 = @CurrentAccount2,     
                   Mezzanine = @Mezzanine,     
                   VendorLoan = @VendorLoan,     
                   Bonds = @Bonds,     
                   BulletDebt = @BulletDebt,     
                   SeniorDebt = @SeniorDebt,     
                   ShortTermLoan = @ShortTermLoan,     
                   BridgeLoan = @BridgeLoan,     
                   Dividends = @Dividends,     
                   Turnover = @Turnover,     
                   EBITDA = @EBITDA,     
                   EBIT = @EBIT,     
                   Workingcapital = @Workingcapital,     
                   CAPEX = @CAPEX,     
                   Netcash_STdebt = @Netcash_STdebt,     
                   Financialdebt = @Financialdebt,     
                   NetProfit = @NetProfit,     
                   Workforce = @Workforce    
             WHERE PortfolioID = @PortfolioID;    
             SET @TransactionStructureID =    
             (    
                 SELECT TOP 1 TransactionStructureID    
                 FROM tbl_portfolioTransactionstructure    
                 WHERE PortfolioID = @portfolioID    
             );    
     END;    
     SELECT 'Success' AS Result,     
            @TransactionStructureID AS 'TransactionStructureID'; 